id: IC4C8834A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T07:27:20+00:00'
last_modified: '2022-06-08T08:47:17.163728+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29481
  title: མན་ངག་བྱེ་བ་རིང་བསྲེལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    07B3:
      image_group_id: I1PD401
      title: ''
      total_pages: 758
      order: 1
      base_file: 07B3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
