id: P009123
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 19:24:05.094253
source_metadata:
  id: bdr:W29481
  title: མན་ངག་བྱེ་བ་རིང་བསྲེལ
  author: ''
  volumes:
    a6b260e94a864879a3b46a700d48c295:
      image_group_id: I1PD401
      title: ''
      volume_number: 1
      total_pages: 758
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
